# This is a config for E2B sandbox template.
# You can use template ID (iu2ej5l729hf9qr318ct) or template name (neo-test-1) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("neo-test-1") # Sync sandbox
# sandbox = await AsyncSandbox.create("neo-test-1") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('neo-test-1')

team_id = "f634dcf4-f422-4f4d-84f6-15dc87fee328"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "neo-test-1"
template_id = "iu2ej5l729hf9qr318ct"
